In [1]:
## Carregamento dos pacotes necessários à execução das rotinas
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import locale
from scipy.stats import linregress
import statsmodels.formula.api as smf
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_rows', None)

In [2]:
## Abertura do arquivo censo de todas as regiões brasileiras
low_memory=False

## Abertura do arquivo da Região Centro-oeste - 2015
censo_co = pd.read_csv('C:/Users/alex/python/dissertacao/MATRICULA_CO.CSV', 
                   sep='|', # nrows=10, 
                   usecols=['TP_ETAPA_ENSINO', 'CO_UF','CO_MESORREGIAO','TP_DEPENDENCIA'])
censo_co.columns = censo_co.columns.str.lower()

## Abertura do arquivo da Região Nordeste - 2015
censo_n = pd.read_csv('C:/Users/alex/python/dissertacao/MATRICULA_NORTE.CSV', 
                   sep='|', # nrows=10, 
                   usecols=['TP_ETAPA_ENSINO', 'CO_UF','CO_MESORREGIAO','TP_DEPENDENCIA'])
censo_n.columns = censo_n.columns.str.lower()

## Abertura do arquivo da Região Norte - 2015
censo_ne = pd.read_csv('C:/Users/alex/python/dissertacao/MATRICULA_NORDESTE.CSV', 
                   sep='|', # nrows=10, 
                   usecols=['TP_ETAPA_ENSINO', 'CO_UF','CO_MESORREGIAO','TP_DEPENDENCIA'])
censo_ne.columns = censo_ne.columns.str.lower()

## Abertura do arquivo da Região Sudeste - 2015
censo_so = pd.read_csv('C:/Users/alex/python/dissertacao/MATRICULA_SUDESTE.CSV', 
                   sep='|', # nrows=10, 
                   usecols=['TP_ETAPA_ENSINO', 'CO_UF','CO_MESORREGIAO','TP_DEPENDENCIA'])
censo_so.columns = censo_so.columns.str.lower()

## Abertura do arquivo da Região Sul - 2015
censo_s = pd.read_csv('C:/Users/alex/python/dissertacao/MATRICULA_SUL.CSV', 
                   sep='|', # nrows=10, 
                   usecols=['TP_ETAPA_ENSINO', 'CO_UF','CO_MESORREGIAO','TP_DEPENDENCIA'])
censo_s.columns = censo_s.columns.str.lower()

In [3]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Centro-oeste - 2015
niveis = []
for row in censo_co['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_co['niveis'] = niveis  

censo_co.groupby('tp_dependencia').niveis.value_counts()

tp_dependencia  niveis
1               tecnico     19343
                medio       13937
                fund2        1847
                eja          1622
                fund1         262
                creche         80
                pre            19
                na              7
2               fund2      561434
                medio      512465
                fund1      301751
                na         174955
                eja        172674
                pre         34423
                tecnico     19744
                creche       1408
3               fund1      670780
                fund2      239932
                na         231648
                pre        219482
                creche     133259
                eja         41866
                medio         832
                tecnico       163
4               fund1      219680
                fund2      151012
                pre         98792
                medio       90576
                creche      66587
                tecnico     54221
                eja         16733
                na          12659
Name: niveis, dtype: int64

In [4]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Norte - 2015
niveis = []
for row in censo_n['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_n['niveis'] = niveis  

censo_n.groupby('tp_dependencia').niveis.value_counts()

tp_dependencia  niveis
1               tecnico      17192
                medio        17061
                fund2         2235
                eja           1317
                fund1          960
                pre            103
                na              61
2               medio       710484
                fund2       592627
                fund1       303590
                eja         230437
                na          185806
                tecnico      15770
                pre           1746
                creche        1000
3               fund1      1373898
                na          598482
                fund2       594086
                pre         421377
                eja         201868
                creche      105961
                medio          449
4               fund1       156205
                fund2        97613
                pre          65246
                medio        61330
                tecnico      52162
                creche       25557
                eja          21510
                na           10677
Name: niveis, dtype: int64

In [5]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Nordeste - 2015
niveis = []
for row in censo_ne['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_ne['niveis'] = niveis  

censo_ne.groupby('tp_dependencia').niveis.value_counts()

tp_dependencia  niveis
1               tecnico      61578
                medio        54854
                eja           4341
                fund2         2138
                fund1          315
                creche         233
                pre            177
                na             153
2               medio      1905955
                fund2       766837
                eja         512298
                na          306474
                fund1       165560
                tecnico      47383
                pre           4088
                creche         702
3               fund1      3612184
                fund2      2429367
                na         1920038
                pre        1066800
                eja         803984
                creche      469380
                medio         9116
                tecnico        671
4               fund1       907434
                fund2       519821
                pre         411328
                medio       244243
                creche      199123
                tecnico     164313
                eja          41169
                na           37741
Name: niveis, dtype: int64

In [6]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Sul - 2015
niveis = []
for row in censo_s['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_s['niveis'] = niveis  

censo_s.groupby('tp_dependencia').niveis.value_counts()

tp_dependencia  niveis
1               tecnico      29539
                medio        24730
                eja           1957
                fund2         1829
                na            1014
                fund1          491
                pre            308
                creche         262
2               fund2      1011238
                medio       927299
                fund1       384896
                na          284043
                eja         217509
                tecnico      50709
                pre           9048
                creche         328
3               fund1      1350456
                na          454707
                pre         440162
                fund2       428115
                creche      358899
                eja          71335
                medio         5979
                tecnico       1119
4               fund1       285647
                fund2       175362
                pre         156380
                creche      150332
                medio       143625
                tecnico     134937
                eja          75019
                na           46333
Name: niveis, dtype: int64

In [7]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Sudeste - 2015
niveis = []
for row in censo_so['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_so['niveis'] = niveis  

censo_so.groupby('tp_dependencia').niveis.value_counts()

tp_dependencia  niveis
1               tecnico      54576
                medio        45343
                fund2         8352
                fund1         5157
                na            3137
                eja           2655
                pre            779
                creche         638
2               medio      2763227
                fund2      2459812
                fund1      1073165
                na          669882
                eja         629025
                tecnico     158068
                pre           1202
                creche         806
3               fund1      3546894
                pre        1488075
                fund2      1470765
                na         1002916
                creche      864256
                eja         343984
                medio        34517
                tecnico      13831
4               fund1      1203078
                fund2       854385
                creche      670261
                medio       510128
                pre         503623
                tecnico     429734
                na          113977
                eja         100566
Name: niveis, dtype: int64

In [8]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Minas Gerais - 2016
censo_mg = censo_so.query('co_uf == 31')

niveis = []
for row in censo_mg['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_mg['niveis'] = niveis  

censo_mg.groupby('tp_dependencia').niveis.value_counts()

c:\users\alex\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

tp_dependencia  niveis
1               tecnico     33654
                medio       17864
                fund2        1730
                fund1        1082
                eja           852
                na            797
                pre           150
2               fund2      798539
                medio      681738
                fund1      391735
                eja        208830
                na         109942
                tecnico      6515
                pre           472
                creche         23
3               fund1      823820
                fund2      348774
                pre        344408
                na         270733
                creche     161970
                eja         79219
                medio        6234
                tecnico      1962
4               fund1      179146
                fund2      126839
                pre        107849
                creche     105549
                tecnico     94618
                medio       81523
                na          23197
                eja         19504
Name: niveis, dtype: int64

In [9]:
## Agrupamento por tipo de estabelecimento de ensino e etapa de ensino - Mesorregião SSM - 2016
censo_ssm = censo_mg.query('co_mesorregiao == 3110')

niveis = []
for row in censo_ssm['tp_etapa_ensino']:
    if row == 1:
        niveis.append('creche')
    elif row == 2:
        niveis.append('pre')
    elif row in [4, 5, 6, 7, 14, 15, 16, 17, 18]:
        niveis.append('fund1')
    elif row in [8, 9, 10, 11, 19, 20, 21, 41]:
        niveis.append('fund2')
    elif row in [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]:
        niveis.append('medio')
    elif row in [39, 40, 68]:  # 68:FIC, ?
        niveis.append('tecnico')        
    elif row in [65, 67, 69, 70, 71, 73, 74]:
        niveis.append('eja')        
    else:
        niveis.append('na')        

censo_ssm['niveis'] = niveis  

censo_ssm.groupby('tp_dependencia').niveis.value_counts()

c:\users\alex\anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

tp_dependencia  niveis
1               tecnico      8972
                medio        2290
                eja           196
                na             73
2               fund2      102288
                medio       78620
                fund1       32208
                eja         26301
                na          12466
                tecnico      2070
                pre            15
                creche         10
3               fund1      113079
                pre         47248
                fund2       32986
                na          29766
                creche      26074
                eja          5505
                medio        1371
                tecnico       174
4               fund1       20949
                fund2       15581
                medio       10938
                pre         10571
                creche      10566
                tecnico      8098
                na           5275
                eja          3036
Name: niveis, dtype: int64